import CryptoKit
import Foundation

public enum ClipboardContent: Equatable, Sendable, Codable {
    case text(String)
    case url(URL)
    /// Kept in memory only. Persisting images would grow without bound for little
    /// benefit; a user who wants one kept can pin it or drop it on the shelf.
    case image(Data)

    /// A stable fingerprint used for de-duplication, so re-copying the same thing
    /// promotes the existing entry rather than adding a twin.
    var fingerprint: String {
        let bytes: Data = switch self {
        case .text(let value): Data(value.utf8)
        case .url(let value): Data(value.absoluteString.utf8)
        case .image(let value): value
        }
        return SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined()
    }

    var isPersistable: Bool {
        switch self {
        case .text, .url: true
        case .image: false
        }
    }

    /// The text a search query is matched against.
    var searchableText: String {
        switch self {
        case .text(let value): value
        case .url(let value): value.absoluteString
        case .image: ""
        }
    }
}

public struct ClipboardEntry: Equatable, Sendable, Codable, Identifiable {
    public let id: UUID
    public var content: ClipboardContent
    public var sourceBundleIdentifier: String?
    public var copiedAt: Date
    public var isPinned: Bool

    public init(
        id: UUID = UUID(),
        content: ClipboardContent,
        sourceBundleIdentifier: String?,
        copiedAt: Date = Date(),
        isPinned: Bool = false
    ) {
        self.id = id
        self.content = content
        self.sourceBundleIdentifier = sourceBundleIdentifier
        self.copiedAt = copiedAt
        self.isPinned = isPinned
    }
}

/// One pasteboard change, before the store has decided whether to keep it.
public struct ClipboardCandidate: Equatable, Sendable {
    public var content: ClipboardContent
    public var sourceBundleIdentifier: String?
    /// Set by password managers via `org.nspasteboard.ConcealedType`. Recording
    /// these would turn the notch into a password log.
    public var isConcealed: Bool
    /// Short-lived internal copies, marked `org.nspasteboard.TransientType` or
    /// `org.nspasteboard.AutoGeneratedType`.
    public var isTransient: Bool

    public init(
        content: ClipboardContent,
        sourceBundleIdentifier: String?,
        isConcealed: Bool = false,
        isTransient: Bool = false
    ) {
        self.content = content
        self.sourceBundleIdentifier = sourceBundleIdentifier
        self.isConcealed = isConcealed
        self.isTransient = isTransient
    }
}
