import AppKit

/// The pasteboard, behind a seam so the module is testable without one.
public protocol PasteboardWatching: Sendable {
    var changeCount: Int { get }
    /// The current pasteboard contents, or nil when there is nothing we keep.
    func read() -> ClipboardCandidate?
    func write(_ content: ClipboardContent)
}

public struct SystemPasteboard: PasteboardWatching {
    /// Markers apps use to say "do not record this". `nspasteboard.org` is the
    /// informal convention every clipboard manager and password manager honours.
    private static let concealedType = "org.nspasteboard.ConcealedType"
    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    public init() {}

    public var changeCount: Int { NSPasteboard.general.changeCount }

    public func read() -> ClipboardCandidate? {
        let pasteboard = NSPasteboard.general
        guard let item = pasteboard.pasteboardItems?.first else { return nil }

        let types = Set(item.types.map(\.rawValue))
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        guard let content = content(of: item, in: pasteboard) else { return nil }

        return ClipboardCandidate(
            content: content,
            sourceBundleIdentifier: source,
            isConcealed: types.contains(Self.concealedType),
            isTransient: !types.isDisjoint(with: Self.transientTypes)
        )
    }

    public func write(_ content: ClipboardContent) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch content {
        case .text(let value):
            pasteboard.setString(value, forType: .string)
        case .url(let value):
            pasteboard.setString(value.absoluteString, forType: .string)
            pasteboard.setData(Data(value.absoluteString.utf8), forType: .URL)
        case .image(let data):
            pasteboard.setData(data, forType: .tiff)
        }
    }

    private func content(of item: NSPasteboardItem, in pasteboard: NSPasteboard) -> ClipboardContent? {
        // Text first: an image copied alongside a filename should still read as
        // what the user thinks they copied.
        if let string = item.string(forType: .string) {
            if let url = URL(string: string), let scheme = url.scheme, scheme.hasPrefix("http") {
                return .url(url)
            }
            return .text(string)
        }
        if let tiff = item.data(forType: .tiff) {
            return .image(tiff)
        }
        if let png = item.data(forType: .png) {
            return .image(png)
        }
        return nil
    }
}
